# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x07project\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"V\n\x0fGetBookResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x08\x62ookInfo\x18\x03 \x01(\x0b\x32\x11.project.BookInfo\"w\n\x11\x43reateBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x1d\n\x05genre\x18\x04 \x01(\x0e\x32\x0e.project.Genre\x12\x16\n\x0epublishingYear\x18\x05 \x01(\x05\"6\n\x12\x43reateBookResponse\x12\x0f\n\x07\x63reated\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"n\n\x08\x42ookInfo\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x1d\n\x05genre\x18\x04 \x01(\x0e\x32\x0e.project.Genre\x12\x16\n\x0epublishingYear\x18\x05 \x01(\x05\".\n\x13GetInventoryRequest\x12\x17\n\x0finventoryNumber\x18\x01 \x01(\x05\"e\n\x14GetInventoryResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12-\n\rinventoryItem\x18\x03 \x01(\x0b\x32\x16.project.InventoryItem\"w\n\rInventoryItem\x12\x17\n\x0finventoryNumber\x18\x01 \x01(\x05\x12!\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x11.project.BookInfoH\x00\"\"\n\x06status\x12\t\n\x05TAKEN\x10\x00\x12\r\n\tAVAILABLE\x10\x01\x42\x06\n\x04Item*G\n\x05Genre\x12\r\n\tUNDEFINED\x10\x00\x12\t\n\x05SCIFI\x10\x01\x12\x0b\n\x07\x46\x41NTASY\x10\x02\x12\n\n\x06HORROR\x10\x03\x12\x0b\n\x07MYSTERY\x10\x04\x32\x8f\x01\n\x04\x42ook\x12>\n\x07GetBook\x12\x17.project.GetBookRequest\x1a\x18.project.GetBookResponse\"\x00\x12G\n\nCreateBook\x12\x1a.project.CreateBookRequest\x1a\x1b.project.CreateBookResponse\"\x00\x32U\n\tInventory\x12H\n\x0cGetInventory\x12\x1c.project.GetInventoryRequest\x1a\x18.project.GetBookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=704
  _GENRE._serialized_end=775
  _GETBOOKREQUEST._serialized_start=23
  _GETBOOKREQUEST._serialized_end=53
  _GETBOOKRESPONSE._serialized_start=55
  _GETBOOKRESPONSE._serialized_end=141
  _CREATEBOOKREQUEST._serialized_start=143
  _CREATEBOOKREQUEST._serialized_end=262
  _CREATEBOOKRESPONSE._serialized_start=264
  _CREATEBOOKRESPONSE._serialized_end=318
  _BOOKINFO._serialized_start=320
  _BOOKINFO._serialized_end=430
  _GETINVENTORYREQUEST._serialized_start=432
  _GETINVENTORYREQUEST._serialized_end=478
  _GETINVENTORYRESPONSE._serialized_start=480
  _GETINVENTORYRESPONSE._serialized_end=581
  _INVENTORYITEM._serialized_start=583
  _INVENTORYITEM._serialized_end=702
  _INVENTORYITEM_STATUS._serialized_start=660
  _INVENTORYITEM_STATUS._serialized_end=694
  _BOOK._serialized_start=778
  _BOOK._serialized_end=921
  _INVENTORY._serialized_start=923
  _INVENTORY._serialized_end=1008
# @@protoc_insertion_point(module_scope)
